### ISSUE TITLE
有没有提供用户上线事件接口

### ISSUE THREAD

**Issue by rightkk** [zhuangjinjin/piccolo#9]
上线的时候，网关有提供上线事件的接口吗，客户端做了自动重连，重连的时候只会握手和绑定userid，业务系统有写数据要上限的时候加载到缓存里，想问你一下有没有上线事件，有的话就可以在事件里做

**Comment by zhuangjinjin** [comment]
刚补上了，UserManager有个registerOnlineHandler，可以注册上线回调
